name = "MyRegistry"
uuid = "6ac37480-5590-414f-914b-4b422e260c9a"
repo = "git@github.com:stefanocampanella/MyRegistry.jl.git"
description = "My private registry"

[packages]
8a5bafa5-7804-46e7-8ed3-a510d2efa4f5 = { name = "TemplateMatching", path = "T/TemplateMatching" }
